.TH "Group" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Group
.SH SYNOPSIS
.br
.PP
.PP
Inherits std::list< Multimedia * >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGroup\fP (const std::string &name)"
.br
.ti -1c
.RI "std::string \fBgetName\fP () const"
.br
.ti -1c
.RI "void \fBdisplay\fP (std::ostream &os) const"
.br
.ti -1c
.RI "void \fBplay\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
