.TH "InputBuffer" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputBuffer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputBuffer\fP (size_t size)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "char * \fBbegin\fP"
.br
.ti -1c
.RI "char * \fBend\fP"
.br
.ti -1c
.RI "SOCKSIZE \fBremaining\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
