.TH "ServerTools" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerTools
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBgetWords\fP (std::string parameters[], const std::string &name)"
.br
.ti -1c
.RI "static std::string \fBprotocolDealer\fP (const std::string &request, \fBMultimediaManager\fP &manager)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
