.TH "swing.src.swing.Client" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
swing.src.swing.Client
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClient\fP (String host, int port)  throws UnknownHostException, IOException "
.br
.ti -1c
.RI "String \fBsend\fP (String request)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "swing\&.src\&.swing\&.Client\&.Client (String host, int port) throws UnknownHostException, IOException\fR [inline]\fP"
Initialise la connexion\&. Renvoie une exception en cas d'erreur\&. 
.SH "Member Function Documentation"
.PP 
.SS "String swing\&.src\&.swing\&.Client\&.send (String request)\fR [inline]\fP"
Envoie une requete au server et retourne sa reponse\&. Noter que la methode bloque si le serveur ne repond pas\&. Envoyer la requete au serveur

.PP
Recuperer le resultat envoye par le serveur

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
