.TH "swing.src.swing.Window" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
swing.src.swing.Window
.SH SYNOPSIS
.br
.PP
.PP
Inherits JFrame, and ActionListener\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindow\fP ()"
.br
.ti -1c
.RI "void \fBactionPerformed\fP (ActionEvent e)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetClient\fP (\fBClient\fP client)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "swing\&.src\&.swing\&.Window\&.Window ()\fR [inline]\fP"
Ajouter des ascenseurs à un JTextArea

.PP
Insertion des boutons dans l'interface

.PP
Champs de saisie de texte

.PP
Menu liste en haut à gauche

.PP
Barre d'outils supérieure

.PP
Barre d'outils inférieure

.PP
Méthodes de JFrame

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
